/* soapWPCEventTrackingServiceSoapProxy.h
   Generated by gSOAP 2.8.15 from soapWPCEventTrackingServiceSoapProxy.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapWPCEventTrackingServiceSoapProxy_H
#define soapWPCEventTrackingServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC WPCEventTrackingServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'WPCEventTrackingServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	WPCEventTrackingServiceSoapProxy();
	/// Construct from another engine state
	WPCEventTrackingServiceSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	WPCEventTrackingServiceSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	WPCEventTrackingServiceSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	WPCEventTrackingServiceSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	WPCEventTrackingServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~WPCEventTrackingServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void WPCEventTrackingServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'addEventLog' (returns error code or SOAP_OK)
	virtual	int addEventLog(_ns1__addEventLog *ns1__addEventLog, _ns1__addEventLogResponse *ns1__addEventLogResponse) { return this->addEventLog(NULL, NULL, ns1__addEventLog, ns1__addEventLogResponse); }
	virtual	int addEventLog(const char *endpoint, const char *soap_action, _ns1__addEventLog *ns1__addEventLog, _ns1__addEventLogResponse *ns1__addEventLogResponse);

	/// Web service operation 'addEventLogList' (returns error code or SOAP_OK)
	virtual	int addEventLogList(_ns1__addEventLogList *ns1__addEventLogList, _ns1__addEventLogListResponse *ns1__addEventLogListResponse) { return this->addEventLogList(NULL, NULL, ns1__addEventLogList, ns1__addEventLogListResponse); }
	virtual	int addEventLogList(const char *endpoint, const char *soap_action, _ns1__addEventLogList *ns1__addEventLogList, _ns1__addEventLogListResponse *ns1__addEventLogListResponse);

	/// Web service operation 'addEventLog' (returns error code or SOAP_OK)
	virtual	int addEventLog_(_ns1__addEventLog *ns1__addEventLog, _ns1__addEventLogResponse *ns1__addEventLogResponse) { return this->addEventLog_(NULL, NULL, ns1__addEventLog, ns1__addEventLogResponse); }
	virtual	int addEventLog_(const char *endpoint, const char *soap_action, _ns1__addEventLog *ns1__addEventLog, _ns1__addEventLogResponse *ns1__addEventLogResponse);

	/// Web service operation 'addEventLogList' (returns error code or SOAP_OK)
	virtual	int addEventLogList_(_ns1__addEventLogList *ns1__addEventLogList, _ns1__addEventLogListResponse *ns1__addEventLogListResponse) { return this->addEventLogList_(NULL, NULL, ns1__addEventLogList, ns1__addEventLogListResponse); }
	virtual	int addEventLogList_(const char *endpoint, const char *soap_action, _ns1__addEventLogList *ns1__addEventLogList, _ns1__addEventLogListResponse *ns1__addEventLogListResponse);
};
#endif
